app/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import RegisterView, UserActivateView

app_name = 'account'

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='signup'),
    path('activate/<slug:uidb64>/<slug:token>/', UserActivateView.as_view(), name='activate'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
]

app/currency/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter
from . import views

from .views import (
    IndexView,
    RateListView,
    RateCreateView,
    RateUpdateView,
    RateDetailView,
    RateDeleteView,
    ContactUsListView,
    ContactUsCreateView,
    ContactUsUpdateView,
    ContactUsDetailView,
    ContactUsDeleteView,
    SourceListView,
    SourceCreateView,
    SourceUpdateView,
    SourceDetailView,
    SourceDeleteView,
    CustomPasswordChangeView,
    CustomPasswordChangeDoneView,
    CustomPasswordResetView,
    CustomPasswordResetDoneView,
    CustomPasswordResetConfirmView,
    CustomPasswordResetCompleteView,
)

app_name = 'currency'

def logout_view(request):
    logout(request)
    return redirect('currency:index')


# Створення маршрутізатора та реєстрація ViewSets
router = DefaultRouter()
# router.register(r'sources', SourceViewSet)
# router.register(r'contactus', ContactUsViewSet)

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

    # Rates URLs
    path('rates/', RateListView.as_view(), name='rate_list'),
    path('rates/create/', RateCreateView.as_view(), name='rate_create'),
    path('rates/update/<int:pk>/', RateUpdateView.as_view(), name='rate_update'),
    path('rates/details/<int:pk>/', RateDetailView.as_view(), name='rate_details'),
    path('rates/delete/<int:pk>/', RateDeleteView.as_view(), name='rate_delete'),

    # ContactUs URLs
    path('contactus/', ContactUsListView.as_view(), name='contactus_list'),
    path('contactus/create/', ContactUsCreateView.as_view(), name='contactus_create'),
    path('contactus/update/<int:pk>/', ContactUsUpdateView.as_view(), name='contactus_update'),
    path('contactus/details/<int:pk>/', ContactUsDetailView.as_view(), name='contactus_details'),
    path('contactus/delete/<int:pk>/', ContactUsDeleteView.as_view(), name='contactus_delete'),

    # Source URLs
    path('source/', SourceListView.as_view(), name='source_list'),
    path('source/create/', SourceCreateView.as_view(), name='source_create'),
    path('source/update/<int:pk>/', SourceUpdateView.as_view(), name='source_update'),
    path('source/details/<int:pk>/', SourceDetailView.as_view(), name='source_details'),
    path('source/delete/<int:pk>/', SourceDeleteView.as_view(), name='source_delete'),

    # Authentication URLs
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('accounts/logout/', logout_view, name='logout'),
    path('accounts/password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', CustomPasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/',
         CustomPasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # API URLs
    path('api/', include(router.urls)),
    path('api/contact_us/', views.contact_us_api, name='contact_us_api'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('currency.urls')),
    path('account/', include('account.urls', namespace='account')),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

app/currency/models.py
from PIL import Image
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.conf import settings
import os
import re


class Rate(models.Model):
    class RateCurrencyChoices(models.IntegerChoices):
        USD = 1, _('USD - US Dollar')
        EUR = 2, _('EUR - Euro')
        HUF = 3, _('HUF - Hungarian Forint')
        CZK = 4, _('CZK - Czech Koruna')
        SEK = 5, _('SEK - Swedish Krona')
        GBP = 6, _('GBP - British Pound')
        RUB = 7, _('RUB - Russian Ruble')

    buy = models.DecimalField(max_digits=6, decimal_places=2)
    sell = models.DecimalField(max_digits=6, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    currency = models.PositiveSmallIntegerField(choices=RateCurrencyChoices.choices)
    source = models.ForeignKey('Source', on_delete=models.SET_NULL, null=True)


class ContactUs(models.Model):
    email_from = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()

    def __str__(self):
        return self.email_from


class Source(models.Model):
    source_url = models.CharField(max_length=255)
    name = models.CharField(max_length=64)
    telephone = models.CharField(max_length=12)
    address_change = models.CharField(max_length=255)
    logo = models.ImageField(
        upload_to='source_logos/',
        default='source_logos/default_logo.png'
    )
    logo_width = models.PositiveIntegerField(default=32)
    logo_height = models.PositiveIntegerField(default=32)

    def save(self, *args, **kwargs):
        media_root = settings.MEDIA_ROOT

        if self.pk:
            original_instance = Source.objects.get(pk=self.pk)

            if original_instance.logo != self.logo:
                # Delete the old logo file
                old_logo_path = os.path.join(media_root, str(original_instance.logo))
                if os.path.exists(old_logo_path):
                    os.remove(old_logo_path)

        super().save(*args, **kwargs)

        img = Image.open(self.logo.path)
        output_size = (self.logo_width, self.logo_height)
        img.thumbnail(output_size)

        img_path = os.path.join(media_root, str(self.logo))

        img.save(img_path)

        original_img_path = os.path.join(media_root, 'source_logos', 'original_' + os.path.basename(img_path))
        self.logo.storage.save(original_img_path, self.logo.storage.open(img_path))

    def __str__(self):
        return self.name


class RequestResponseLog(models.Model):
    path = models.CharField(max_length=255)
    request_method = models.CharField(max_length=10)
    time = models.IntegerField()


def clean_phone_number(sender, instance, **kwargs):
    if instance.telephone:
        instance.telephone = re.sub(r'\D', '', instance.telephone)


models.signals.pre_save.connect(clean_phone_number, sender=Source)

app/currency/views.py
from django.views.generic import (
    ListView, CreateView, UpdateView, DetailView,
    DeleteView, TemplateView
)
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from .models import ContactUs, Rate, Source
from .forms import ContactUsForm, SourceForm, RateForm
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeView,
    PasswordChangeDoneView,
)
from .forms import CustomPasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.db.models import Q
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.contrib.auth.models import User
from .filters import RateFilter, ContactUsFilter, SourceFilter
from .serializers import ContactUsSerializer, SourceSerializer
import re

from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response


class IndexView(TemplateView):
    template_name = 'index.html'


class CrispyFormMixin:
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.helper = FormHelper()
        form.helper.add_input(Submit('submit', self.submit_label))
        return form


class RateListView(ListView):
    model = Rate
    template_name = 'rate_list.html'
    context_object_name = 'rates'
    paginate_by = 10

    def get_queryset(self):
        rates = Rate.objects.all().order_by('created')

        # Фільтрація
        self.filter = RateFilter(self.request.GET, queryset=rates)
        return self.filter.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.filter

        # Отримуємо параметри фільтрації, окрім 'page'
        context['filter_params'] = '&'.join(
            f'{key}={value}'
            for key, value in self.request.GET.items()
            if key != 'page'
        )
        return context


class RateCreateView(CrispyFormMixin, CreateView):
    model = Rate
    form_class = RateForm
    template_name = 'rate_create.html'
    success_url = reverse_lazy('currency:rate_list')
    submit_label = 'Create Rate'


class RateUpdateView(CrispyFormMixin, UserPassesTestMixin, UpdateView):
    login_url = reverse_lazy('currency:login')
    model = Rate
    form_class = RateForm
    template_name = 'rate_update.html'
    success_url = reverse_lazy('currency:rate_list')
    submit_label = 'Update Rate'

    def test_func(self):
        return self.request.user.is_superuser


class RateDetailView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('currency:login')
    model = Rate
    template_name = 'rate_details.html'
    context_object_name = 'rate'


class RateDeleteView(CrispyFormMixin, UserPassesTestMixin, DeleteView):
    login_url = reverse_lazy('currency:login')
    model = Rate
    template_name = 'rate_delete.html'
    success_url = reverse_lazy('currency:rate_list')
    submit_label = 'Delete Rate'

    def test_func(self):
        return self.request.user.is_superuser


class ContactUsListView(ListView):
    model = ContactUs
    template_name = 'contactus_list.html'
    context_object_name = 'contacts'
    paginate_by = 10

    def get_queryset(self):
        contacts = ContactUs.objects.all().order_by('id')

        # Фільтрація і сортування
        search_query = self.request.GET.get('search', '')
        if search_query:
            contacts = contacts.filter(Q(subject__icontains=search_query) | Q(message__icontains=search_query))

        self.filter = ContactUsFilter(self.request.GET, queryset=contacts)
        return self.filter.qs.order_by('-created_at')  # сортування за датою

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.filter

        # Отримуємо параметри фільтрації, окрім 'page'
        context['filter_params'] = '&'.join(
            f'{key}={value}'
            for key, value in self.request.GET.items()
            if key != 'page'
        )
        return context


class ContactUsCreateView(CrispyFormMixin, CreateView):
    model = ContactUs
    form_class = ContactUsForm
    template_name = 'contactus_create.html'
    success_url = reverse_lazy('currency:contactus_list')
    submit_label = 'Create Contact Us'

    def form_valid(self, form):
        response = super().form_valid(form)
        serializer = ContactUsSerializer(data=form.cleaned_data)
        if serializer.is_valid():
            serializer.save()
            messages.success(self.request, 'Контакт успішно створений.')
        else:
            # Виводимо помилки в консоль
            print("Serializer errors: ", serializer.errors)

            # Додаємо складнішу логіку обробки помилок
            error_messages = []
            for field, errors in serializer.errors.items():
                for error in errors:
                    error_messages.append(f"Поле {field}: {error}")

            for error_message in error_messages:
                messages.error(self.request, error_message)

        return response


class ContactUsUpdateView(CrispyFormMixin, UpdateView):
    model = ContactUs
    form_class = ContactUsForm
    template_name = 'contactus_update.html'
    success_url = reverse_lazy('currency:contactus_list')
    submit_label = 'Update Contact Us'


class ContactUsDetailView(DetailView):
    model = ContactUs
    template_name = 'contactus_details.html'
    context_object_name = 'contact'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['contacts'] = ContactUs.objects.all()
        return context


class ContactUsDeleteView(CrispyFormMixin, DeleteView):
    model = ContactUs
    template_name = 'contactus_delete.html'
    success_url = reverse_lazy('currency:contactus_list')
    submit_label = 'Delete Contact Us'


class SourceListView(ListView):
    model = Source
    template_name = 'source_list.html'
    context_object_name = 'sources'
    paginate_by = 10

    def get_queryset(self):
        sources = Source.objects.all().order_by('id')

        # Фільтрація
        self.filter = SourceFilter(self.request.GET, queryset=sources)
        return self.filter.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.filter

        # Отримуємо параметри фільтрації, окрім 'page'
        context['filter_params'] = '&'.join(
            f'{key}={value}'
            for key, value in self.request.GET.items()
            if key != 'page'
        )
        return context


class SourceCreateView(CrispyFormMixin, CreateView):
    model = Source
    form_class = SourceForm
    template_name = 'source_create.html'
    success_url = reverse_lazy('currency:source_list')
    submit_label = 'Create Source'


class SourceUpdateView(CrispyFormMixin, UpdateView):
    model = Source
    form_class = SourceForm
    template_name = 'source_update.html'
    success_url = reverse_lazy('currency:source_list')
    submit_label = 'Update Source'


class SourceDetailView(DetailView):
    model = Source
    template_name = 'source_details.html'
    context_object_name = 'source'


class SourceDeleteView(CrispyFormMixin, DeleteView):
    model = Source
    template_name = 'source_delete.html'
    success_url = reverse_lazy('currency:source_list')
    submit_label = 'Delete Source'


class CustomPasswordResetView(auth_views.PasswordResetView):
    template_name = 'registration/password_reset_form.html'
    email_template_name = 'registration/password_reset_email.html'
    success_url = reverse_lazy('currency:password_reset_done')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['protocol'] = 'http'
        return context


class CustomPasswordChangeView(UserPassesTestMixin, LoginRequiredMixin, PasswordChangeView):
    form_class = CustomPasswordChangeForm
    template_name = 'registration/change_password.html'
    success_url = reverse_lazy('custom_password_change_done')

    def test_func(self):
        return self.request.user.is_authenticated

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Пароль успішно змінено.')
        return response


class CustomPasswordChangeDoneView(LoginRequiredMixin, PasswordChangeDoneView):
    template_name = 'registration/password_change_done.html'


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'registration/password_reset_done.html'


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'registration/password_reset_confirm.html'


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'registration/password_reset_complete.html'


@receiver(pre_save, sender=User)
def clean_user_phone_number(sender, instance, **kwargs):
    if hasattr(instance, 'phone') and instance.phone:
        instance.phone = re.sub(r'\D', '', instance.phone)


@api_view(['POST'])
def contact_us_api(request):
    if request.method == 'POST':
        serializer = ContactUsSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

app/currency/templates/contactus_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Create Contact Us
{% endblock title %}

{% block content %}
    <h1>Create Contact Us</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <p></p>
    <a href="{% url 'currency:contactus_list' %}">Back to Source List</a>
{% endblock content %}

app/currency/templates/contactus_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Delete Contact Us
{% endblock title %}

{% block content %}
    Are you sure you want to delete rate with id: {{ object.id }}?

    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, delete!</button>
    </form>
    <a href="{% url 'currency:contactus_list' %}">Back to Source List</a>

{% endblock content %}

app/currency/templates/contactus_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Contactus Details
{% endblock title %}

{% block content %}
        Id: {{ contact.id }} <br>
        Email From: {{ contact.email_from }}  <br>
        Subject: {{ contact.subject }} <br>
        Message: {{ contact.message }} <br>
    <p></p>
    <a href="{% url 'currency:contactus_list' %}">Back to Source List</a>
{% endblock content %}

app/currency/templates/contactus_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Contact Us List
{% endblock title %}

{% block content %}
    <h1>Contact Us List</h1>
    <form method="get">
    {{ filter.form.as_p }}
    <button type="submit">Фільтрувати</button>
    </form>
    <table>
        <tr>
            <th>ID</th>
            <th>Email From</th>
            <th>Subject</th>
            <th>Message</th>
            <th>Actions</th>
        </tr>
        {% for contact in contacts %}
            <tr>
                <td>{{ contact.id }}</td>
                <td>{{ contact.email_from }}</td>
                <td>{{ contact.subject }}</td>
                <td>{{ contact.message }}</td>
                <td>
                    <a href="{% url 'currency:contactus_details' contact.pk %}">Details</a>
                    <a href="{% url 'currency:contactus_update' contact.pk %}">Edit</a>
                    <form method="post" action="{% url 'currency:contactus_delete' contact.pk %}" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" onclick="return confirm('Are you sure you want to delete this contact?')">Delete</button>
                    </form>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="5">No contacts found.</td>
            </tr>
        {% endfor %}
    </table>

    <div class="pagination">
        <span class="step-links">
            {% if contacts.has_previous %}
                <a href="?page=1&{{ filter_params }}">&laquo; перша</a>
                <a href="?page={{ rates.previous_page_number }}&{{ filter_params }}">попередня</a>
            {% endif %}

            <span class="current">
                Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}.
            </span>

            {% if contacts.has_next %}
                <a href="?page={{ rates.next_page_number }}&{{ filter_params }}">наступна</a>
                <a href="?page={{ contacts.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

    <hr>

    <h2>Create Contact Us</h2>
    <form method="post" action="{% url 'currency:contactus_create' %}">
        {% csrf_token %}
        {{ form.as_p|crispy }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

app/currency/templates/contactus_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Edit Contact Us</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <p></p>
    <a href="{% url 'currency:contactus_list' %}">Back to Contact Us List</a>
{% endblock %}

app/currency/templates/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Welcome to my website!</h1>
    <p>This is the home page.</p>
{% endblock %}

app/currency/templates/rate_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Create Rate
{% endblock title %}

{% block content %}
    Create Rate Form

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>

{% endblock content %}

app/currency/templates/rate_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Delete Rate
{% endblock title %}

{% block content %}
    Are you sure you want to delete rate with id: {{ object.id }}?

    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, delete!</button>
    </form>
    <a href="{% url 'currency:rate_list' %}">Back to Source List</a>

{% endblock content %}

app/currency/templates/rate_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Rate List
{% endblock title %}

{% block content %}
    <h1>Rate List</h1>
    <form method="get">
    {{ filter.form.as_p }}
    <button type="submit">Фільтрувати</button>
    </form>
    <table>
        <tr>
            <th>ID</th>
            <th>Buy</th>
            <th>Sell</th>
            <th>Created</th>
            <th>Currency</th>
            <th>Source</th>
            <th>Actions</th>
        </tr>
        {% for rate in rates %}
            <tr>
                <td>{{ rate.id }}</td>
                <td>{{ rate.buy }}</td>
                <td>{{ rate.sell }}</td>
                <td>{{ rate.created }}</td>
                <td>{{ rate.get_currency_display }}</td>
                <td>{{ rate.source }}</td>
                <td>
                    <a href="{% url 'currency:rate_details' rate.pk %}">Details</a>
                    <a href="{% url 'currency:rate_update' rate.pk %}">Edit</a>
                    <form method="post" action="{% url 'currency:rate_delete' rate.pk %}" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" onclick="return confirm('Are you sure you want to delete this rate?')">Delete</button>
                    </form>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="7">No rates found.</td>
            </tr>
        {% endfor %}
    </table>

    <div class="pagination">
    <span class="step-links">
        {% if rates.has_previous %}
            <a href="?page=1&{{ filter_params }}">&laquo; перша</a>
            <a href="?page={{ rates.previous_page_number }}&{{ filter_params }}">попередня</a>
        {% endif %}

        <span class="current">
            Сторінка {{ rates.number }} з {{ rates.paginator.num_pages }}.
        </span>

        {% if rates.has_next %}
            <a href="?page={{ rates.next_page_number }}&{{ filter_params }}">наступна</a>
            <a href="?page={{ rates.paginator.num_pages }}">остання &raquo;</a>
        {% endif %}
    </span>
    </div>

    <hr>

    <h2>Create Rate</h2>
    <form method="post" action="{% url 'currency:rate_create' %}">
        {% csrf_token %}
        {{ form.as_p|crispy }}
        <button type="submit">Create</button>
    </form>
{% endblock content %}

app/currency/templates/rate_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Update Rate
{% endblock title %}

{% block content %}
    Update Rate Form

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <p></p>
    <a href="{% url 'currency:rate_list' %}">Back to Source List</a>

{% endblock content %}

app/currency/templates/source_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Create Source
{% endblock title %}

{% block content %}
    <h1>Create Source</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
    <p></p>
    <a href="{% url 'currency:source_list' %}">Back to Source List</a>
{% endblock content %}

app/currency/templates/source_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Source Details</h1>
    <p>Source URL: {{ source.source_url }}</p>
    <p>Name: {{ source.name }}</p>
    <p>Telephone: {{ source.telephone }}</p>
    <p>Address Change: {{ source.address_change }}</p>
    <p>Logo: <img src="{{ source.logo.url }}"
                         alt="Logo"
                         width="{{ source.logo_width }}"
                         height="{{ source.logo_height }}"></p>
    <p></p>
    <a href="{% url 'currency:source_list' %}">Back to Source List</a>
{% endblock %}

app/currency/templates/source_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Source List</h1>
    <form method="get">
    {{ filter.form.as_p }}
    <button type="submit">Фільтрувати</button>
    </form>
    <table>
        <tr>
            <th>Source URL</th>
            <th>Name</th>
            <th>Telephone</th>
            <th>Address Change</th>
            <th>Logo</th>
            <th>Actions</th>
        </tr>
        {% for source in sources %}
            <tr>
                <td>{{ source.source_url }}</td>
                <td>{{ source.name }}</td>
                <td>{{ source.telephone }}</td>
                <td>{{ source.address_change }}</td>
                <td><img src="{{ source.logo.url }}"
                         alt="Logo"
                         width="{{ source.logo_width }}"
                         height="{{ source.logo_height }}"></td>
                <td>
                    <a href="{% url 'currency:source_details' source.pk %}">Details</a>
                    <a href="{% url 'currency:source_update' source.pk %}">Edit</a>
                    <form method="post" action="{% url 'currency:source_delete' source.pk %}" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit"
                                onclick="return confirm('Are you sure you ' +
                                 'want to delete this source?')">Delete</button>
                    </form>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="5">No sources available at the moment. Please check back later.</td>
            </tr>
        {% endfor %}
    </table>

    <div class="pagination">
        <span class="step-links">
            {% if sources.has_previous %}
                <a href="?page=1&{{ filter_params }}">&laquo; перша</a>
                <a href="?page={{ rates.previous_page_number }}&{{ filter_params }}">попередня</a>
            {% endif %}

            <span class="current">
                Page {{ sources.number }} of {{ sources.paginator.num_pages }}.
            </span>

            {% if sources.has_next %}
                <a href="?page={{ rates.next_page_number }}&{{ filter_params }}">наступна</a>
                <a href="?page={{ sources.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

    <hr>

    <h2>Create Source</h2>
    <form method="post" action="{% url 'currency:source_create' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Create</button>
    </form>
{% endblock %}

app/currency/templates/source_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Edit Source</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Update</button>
    </form>
    <p></p>
    <a href="{% url 'currency:source_list' %}">Back to Source List</a>
{% endblock %}